name: Uliks
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5

dev_dependencies:
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.0
  permission_handler: ^11.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Spartan
      fonts:
        - asset: assets/fonts/Spartan-Regular.ttf
        - asset: assets/fonts/Spartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/Spartan-SemiBold.ttf
          weight: 600
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
